source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'BTICoreDataKitDemoProject' do
	pod 'BTIKit', :git =>'https://github.com/BriTerIdeas/BTIKit.git'
end

target 'BTICoreDataKitDemoProjectTests' do
	pod 'BTIKit', :git =>'https://github.com/BriTerIdeas/BTIKit.git'
end